# Generated by Django 3.2.16 on 2022-11-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatview',
            name='avatar',
            field=models.CharField(default='/src/assets/man-4.png', max_length=200),
        ),
    ]
